import { BundleData } from "./BundleData";
import { BundleName } from "./BundleName";

export const SoundPath = {

    button_click: new BundleData(BundleName.Assets, "audios/button_click"),
    archer_ATK: new BundleData(BundleName.Assets, "audios/archer_ATK"),
    battle_begin: new BundleData(BundleName.Assets, "audios/battle_begin"),
    battle_BGM01: new BundleData(BundleName.Assets, "audios/battle_BGM01"),
    battle_BGM02: new BundleData(BundleName.Assets, "audios/battle_BGM02"),
    enemy_hit: new BundleData(BundleName.Assets, "audios/enemy_hit"),
    level_up: new BundleData(BundleName.Assets, "audios/level_up"),
    main_BGM: new BundleData(BundleName.Assets, "audios/main_BGM"),
    success: new BundleData(BundleName.Assets, "audios/success"),
    fail: new BundleData(BundleName.Assets, "audios/fail"),
    get: new BundleData(BundleName.Assets, "audios/get"),
    boss_atk: new BundleData(BundleName.Assets, "audios/boss_atk"),
    boss_come: new BundleData(BundleName.Assets, "audios/boss_come"),
    reward_get: new BundleData(BundleName.Assets, "audios/reward_get"),
    skill_1001: new BundleData(BundleName.Assets, "audios/skill_01"),
    skill_01_effect: new BundleData(BundleName.Assets, "audios/skill_01_effect"),
    skill_1002: new BundleData(BundleName.Assets, "audios/skill_02"),
    skill_02_effect: new BundleData(BundleName.Assets, "audios/skill_02_effect"),
    skill_1003: new BundleData(BundleName.Assets, "audios/skill_03"),
    skill_1004: new BundleData(BundleName.Assets, "audios/skill_04"),
    skill_1005: new BundleData(BundleName.Assets, "audios/skill_05"),
    skill_05_effect: new BundleData(BundleName.Assets, "audios/skill_05_effect"),
    skill_1006: new BundleData(BundleName.Assets, "audios/skill_06"),
    skill_1007: new BundleData(BundleName.Assets, "audios/skill_07"),
    skill_1008: new BundleData(BundleName.Assets, "audios/skill_08"),
    skill_1009: new BundleData(BundleName.Assets, "audios/skill_09"),
    skill_09_effect: new BundleData(BundleName.Assets, "audios/skill_09_effect"),
    skill_1010: new BundleData(BundleName.Assets, "audios/skill_10"),
    skill_10_effect: new BundleData(BundleName.Assets, "audios/skill_10_effect"),
}

export enum SoundEnum {
    button_click = 0,
    archer_ATK,
    battle_begin,
    battle_BGM01,
    battle_BGM02,
    enemy_hit,
    level_up,
    main_BGM,
    success,
    fail,
    skill_01,
    skill_01_effect,
    skill_02,
    skill_02_effect,
    skill_03,
    skill_04,
    skill_05,
    skill_06,
    skill_07,
    skill_08,
    skill_09,
    skill_10,
}
